export const BASE_URL = process.env.REACT_APP_API_URL
// public costants
export const LOGIN = "auth/login"
export const REGISTER = "auth/register"
export const FORGOT_PASSWORD = "auth/forgot-password"
export const RESET_PASSWORD = "auth/reset-password"
export const BRANDS = "brands/"
export const ICECREAM = "ice-creams/"
export const ICECREAM_BY_BRAND = "ice-creams-by-brand/"
export const MESSAGES = "messages"
export const PAYMENT_VERIFY = "verify-payment/"
export const RETRY_PAYMENT = "retry-payment/"
export const IMAGE_URL = BASE_URL + "images/"
export const PUBLIC_REVIEWS = BASE_URL + "user-reviews/"

//user api constants
export const MY_ORDERS = "user/my-orders"
export const MY_ORDER_DETAILS = "user/my-order-details/"
export const PLACE_ORDER = "user/order/place"
export const ADDRESS_DEFAULT = "user/address-default/"
export const PROFILE = "user/profile"
export const ADDRESS = "user/address/"
export const REVIEW = "user/reviews/"
export const CANCEL_ORDER = "user/order-cancel/"

//ADMIN API
export const ADMIN = "admin/"
export const STAFF = "admin/staff/"
export const CUSTOMERS = "admin/customers"
export const REVIEWS = "admin/reviews"
export const USER_REVIEWS = "admin/user-reviews"
export const ORDERS = "admin/orders/"
export const ORDER_STATUS_UPDATE = "admin/order-status-update/"
export const DASHBOARD = "admin/dashboard"
export const CONTACT_MESSAGES = "admin/messages"
